# Build Docker image for this app using Azure Pipelines
trigger:
  branches: 
    include: 
    - master
  paths:
    include:
    - src
    - test

pr:
  branches: 
    include: 
    - master
  paths:
    include:
    - src
    - test

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'booklibrary-netcore'
  dockerFile: 'src/BookLibrary/Dockerfile'
  # define two more variables dockerId and pswd in the build pipeline in UI

steps:
- script: |
    docker build -f $(dockerFile) -t $(dockerId)/$(imageName):ci-$(Build.BuildId) -t $(dockerId)/$(imageName):latest .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName):ci-$(Build.BuildId)
    docker push $(dockerId)/$(imageName):latest
