trigger:
  branches: 
    include: 
    - master
  paths:
    include:
    - src
    - test

pr:
  branches: 
    include: 
    - master
  paths:
    include:
    - src
    - test

# To adopt this build pipeline to your environment, update the following
# variables:
# - dockerRegistryServiceConnection: A reference to your registry
# - imageRepository: The repository to push the image to
variables:
  buildConfiguration: 'Release'
  buildContext: '.'
  dockerfilePath: 'src/BookLibrary/Dockerfile'
  dockerRegistryServiceConnection: 'dockerhub/joergjo'
  dotnetVersion: 2.2.x
  imageRepository: 'joergjo/booklibrary-netcore'
  tag: 'ci-$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: PR_Validation
      condition: eq(variables['Build.Reason'], 'PullRequest')
      pool: 
        vmImageName: $(vmImageName)
      steps:
      - task: UseDotNet@2
        displayName: 'Install latest .NET Core SDK' 
        inputs:
          packageType: sdk
          version: $(dotnetVersion) 
          installationPath: '$(Agent.ToolsDirectory)/dotnet'
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: |
            **/BookLibrary.Test.csproj
          arguments: '--configuration $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: |
            **/BookLibrary.Test.csproj
          arguments: '--configuration $(buildConfiguration)'
    - job: Build_Container_Images
      condition: in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual')
      pool: 
        vmImageName: $(vmImageName)
      steps:
        - task: Docker@2
          displayName: 'Build and push image to container'
          inputs:
            command: buildAndPush
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            buildContext: $(buildContext)
            containerRegistry: $(dockerRegistryServiceConnection)
            tags: |
              $(tag)
              latest
  