version: "3.4"

volumes:
  mongodata:

services:
  mongodb:
    image: mongo:${MONGO_TAG:-4.2}

  webapi:
    build:
      context: .
      dockerfile: src/BookLibrary/Dockerfile
    image: booklibrary-netcore
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ConnectionStrings__DefaultConnection=${BOOKLIBRARY_MONGODB_CONNECTION:-mongodb://mongodb}
    depends_on:
      - mongodb
