version: "3"

volumes:
  mongodata:

services:
  mongodb:
    image: mongo:4.2

  webapi:
    build:
      context: .
      dockerfile: src/BookLibrary/Dockerfile
    image: booklibrary-netcore
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ConnectionStrings__DefaultConnection=${BOOKLIBRARY_MONGODB_CONNECTION:-mongodb://localhost}
      - Logging__LogLevel__Default=${BOOKLIBRARY_LOGLEVEL:-Information}
    depends_on:
      - mongodb
