apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booklibrary
spec:
  rules:
  - host: booklibrary.<DNS_ZONE>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booklibrary-svc
            port:
              name: http
