apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: booklibrary
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: booklibrary
    spec:
      containers:
      - name: booklibrary
        image: joergjo/booklibrary-netcore:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: booklibrary-config
        - secretRef:
            name: booklibrary-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: booklibrary-svc
spec:
  ports:
  - port: 80
  selector:
    app: booklibrary